const express = require('express');
const router = express.Router();
const authorize = require('../auth/auth');
const apiController = require('../controllers/apiControllers');

router.post('/login', apiController.login);
router.post('/sessions/:id/login', apiController.sessionLogin);
router.post('/user-add', authorize(['superadmin', 'hr']), apiController.addUser);
router.get('/users', authorize(['superadmin', 'hr', 'hse', 'facilitator']), apiController.getUsers);
router.put('/users/:id', authorize(['superadmin', 'hr', 'hse']), apiController.updateUser);
router.patch('/users/:id/status', authorize(['superadmin', 'hr']), apiController.toggleUserStatus);
router.get('/me', authorize(), apiController.getMe);
router.delete('/users/:id', authorize(['superadmin', 'hr', 'hse']), apiController.deleteUser);
router.get('/users/:id', authorize(['superadmin', 'hr', 'hse', 'facilitator']), apiController.getUser);
router.post('/trainings', authorize(['superadmin', 'hse']), apiController.createTraining);
router.get('/trainings', authorize(['superadmin', 'hr', 'hse', 'facilitator']), apiController.getTrainings);
router.get('/trainings/:id', authorize(['superadmin', 'hr', 'hse', 'facilitator']), apiController.getTraining);
router.put('/trainings/:id', authorize(['superadmin', 'hse']), apiController.updateTraining);
router.delete('/trainings/:id', authorize(['superadmin', 'hse']), apiController.deleteTraining);
router.post('/trainings/:id/questions', authorize(['superadmin', 'hse']), apiController.addTrainingQuestions);
router.post('/sessions', authorize(['superadmin', 'hr', 'hse']), apiController.createSession);
router.get('/sessions/:id', authorize(['superadmin', 'hr', 'hse', 'facilitator']), apiController.getSession);
router.post('/sessions/:id/start', authorize(['superadmin', 'hse', 'facilitator']), apiController.startSession);
router.post('/sessions/:id/end', authorize(['facilitator', 'superadmin', 'hse']), apiController.endSession);
router.post('/sessions/:id/enroll', authorize(['superadmin', 'hr']), apiController.enrollSession);
router.get('/sessions/:id/trainees', authorize(['superadmin', 'hr', 'hse', 'facilitator']), apiController.getSessionTrainees);
router.post('/sessions/:id/scan', apiController.scanSessionQR);
router.get('/sessions/public/:id', apiController.getPublicSession);
router.get('/sessions/:id/attendance', authorize(['superadmin', 'hr', 'hse', 'facilitator']), apiController.getSessionAttendance);
router.get('/sessions/:id/questions', apiController.getSessionQuestions);
router.post('/sessions/:id/test/attempt', apiController.submitSessionAttempt);
router.get('/sessions/:id/results', authorize(['HR', 'facilitator', 'superadmin']), apiController.getSessionResults);
router.get('/sessions/:id/attempts', authorize(['hr', 'facilitator', 'superadmin']), apiController.getSessionAttempts);
router.get('/trainees/:traineeId/history', authorize(['superadmin', 'hr', 'hse', 'facilitator', 'trainee']), apiController.getTraineeHistory);
router.get('/reports/attempts', authorize(['superadmin', 'hr']), apiController.getReportsAttempts);
router.get('/sessions', authorize(['superadmin', 'hr', 'hse', 'facilitator']), apiController.getSessionsAll);
router.get('/questionsets/:id', authorize(['superadmin', 'hr', 'hse', 'facilitator']), apiController.getQuestionSet);
router.get('/sessions/:id/trainee-attempts', apiController.getSessionTraineeAttempts);
router.get('/profile/stats', authorize(), apiController.getProfileStats);
router.put('/me/edit', authorize(), apiController.editMe);
router.put('/admin/users/:id/edit', authorize(['superadmin', 'hr', 'hse']), apiController.adminEditUser);

module.exports = router;
